import type { Metadata } from "next";
import { Providers } from "./providers";
import "./style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDev = process.env.NODE_ENV === 'development'
  return (
    <html lang="en" suppressHydrationWarning={isDev}>
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
      </head>
      <body id="body" style={{minHeight: "100vh", display: "flex", flexWrap: "wrap", flexDirection: "column"}}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
